package Util;

import java.util.Arrays;
import java.util.List;

public class CatBreeds {
    public static final List<String> LIST = Arrays.asList(
            "Mixed",
            "Unknown",
            "Abyssinian",
            "American Bobtail, Long-Haired",
            "American Bobtail, Short-Haired",
            "American Curl",
            "American Ringtail",
            "American Short Hair",
            "American Wire Hair",
            "Anatolian",
            "Angora",
            "Australian Mist, Non-spotted",
            "Australian Mist, Spotted",
            "Balinese",
            "Bengal",
            "Birman",
            "Bombay",
            "Brazilian Long Hair",
            "Brazilian Short Hair",
            "British Long Hair",
            "British Red Spot",
            "British Short Hair",
            "Burmese",
            "Burmilla",
            "Calico",
            "California Spangled",
            "Chantilly (Tiffany)",
            "Chartreux",
            "Chausie",
            "Chinchilla",
            "Cornish Rex",
            "Cross Breed",
            "Cymric",
            "Devon Rex",
            "Domestic Leopard Cat",
            "Domestic Long Hair",
            "Domestic Medium Hair",
            "Domestic Short Hair",
            "Don Hairless",
            "Don Sphynx",
            "Egyptian Black",
            "Egyptian Mau",
            "European Short Hair",
            "Exotic Long Hair",
            "Exotic Short Hair",
            "Foreign White",
            "German Rex",
            "Havana Brown",
            "Highland Fold",
            "Himalayan",
            "Japanese Bobtail",
            "Javanese",
            "Khao Manee",
            "Korat",
            "Kurilean Bobtail, Long-Haired",
            "Kurilean Bobtail, Short-Haired",
            "LaPerm, Long-Haired",
            "LaPerm, Short-Haired",
            "Maine Coon",
            "Maltese",
            "Manx, Long-Haired",
            "Manx, Short-Haired",
            "Manxamese",
            "Minskin",
            "Munchkin (Munchk), Long-Haired",
            "Munchkin (Munchk), Short-Haired",
            "Nebelung",
            "Neva Masquerade (Colourpoint Siberian Forest Cat)",
            "Norwegian Forest",
            "Ocicat",
            "Ojos Azules",
            "Oregon Rex",
            "Oriental Long Hair",
            "Oriental Short Hair",
            "Persian, Tabby",
            "Peterbald",
            "PixieBob",
            "Ragamuffin",
            "Ragdoll",
            "Savannah",
            "Scottish Fold, Long-Haired",
            "Scottish Fold, Short-Haired",
            "Scottish Wildcat",
            "Selkirk Rex",
            "Serengeti",
            "Seychellois Long Hair",
            "Seychellois Short Hair",
            "Siamese",
            "Siberian",
            "Siberian Forest Cat",
            "Singapura",
            "Snowshoe",
            "Sokoke (African Short Hair)",
            "Sphynx",
            "Tonkinese",
            "Toyger",
            "Turkish Angora",
            "Turkish Van",
            "Turkish Vankedisi (Van Kedisi)",
            "York Chocolate",
            "American Bobtail (unspecified)",
            "Asian",
            "Australian Mist (unspecified)",
            "British Black Tipped",
            "British Blue",
            "Exotic (unspecified)",
            "LaPerm (unspecified)",
            "Manx (unspecified)",
            "Munchkin (Munchk) (unspecified)",
            "Oriental (unspecified)",
            "Scottish Fold (unspecified)",
            "Thai",
            "Domestic cat (hair length unspecified)",
            "Russian (unspecified)",
            "Russian Black",
            "Russian Blue",
            "Russian Tabby",
            "Russian White",
            "Rex (unspecified)",
            "Persian (unspecified)",
            "Persian, Blue",
            "Persian, Colourpoint",
            "Persian, Smoke",
            "Purebred cross (Feline)",
            "Breed not listed (Feline)",
            "Colourpoint Short Hair",
            "Allerca Hypoallergenic Cat",
            "Arabian Mau",
            "Ashanti",
            "Bahraini Dilmun Cat ( Delmun Cat )",
            "Bambino",
            "European Long Hair",
            "European (unspecified)",
            "Polydactyl cat ( Hemingway cat )",
            "European Tiger Cat",
            "Minuet ( Napoleon )",
            "Tiffanie",
            "Somali Short Hair",
            "Somali (unspecified)",
            "Somali Long Hair"
    );
}
