package Util;

import java.util.Arrays;
import java.util.List;

public class DogBreeds {
    public static final List<String> LIST = Arrays.asList(
            "Abruzzenhund",
            "Affenpinscher",
            "Afghan Hound",
            "African Wild Dog",
            "Africanis",
            "Airedale Terrier",
            "Akbash",
            "Akita",
            "Akita - Mix",
            "Alaskan Klee Kai",
            "Alaskan Malamute",
            "American Bulldog",
            "American English Coonhound",
            "American Eskimo Dog",
            "American Foxhound",
            "American Hairless Terrier",
            "American Leopard Hound",
            "American Pit Bull Terrier",
            "American Staffordshire Terrier",
            "American Staffordshire Terrier - Mix",
            "American Water Spaniel",
            "Anatolian Shepherd Dog",
            "Anglos-Francais de Moyenne Venerie",
            "Anglos-Francaises de Petite Venerie",
            "Appenzeller Sennenhund",
            "Arctic Fox",
            "Arubian Cunucu Dog",
            "Aryan Molossus",
            "Aussiedoodle - Mini",
            "Aussiedoodle - Standard",
            "Australian Cattle Dog",
            "Australian Kelpie",
            "Australian Shepherd",
            "Australian Shepherd - Mini",
            "Australian Shepherd - Standard",
            "Australian Terrier",
            "Azawakh",
            "Bandog ( Bandogge )(unspecified)",
            "Barbet",
            "Basenji",
            "Basset Fauve de Bretagne",
            "Basset Hound",
            "Bavarian Mountain Scent Hound",
            "Beagle",
            "Beagle - Mix",
            "Bearded Collie",
            "Beauceron",
            "Bedlington Terrier",
            "Belgian Groenendael",
            "Belgian Laekenois",
            "Belgian Malinois",
            "Belgian Sheepdog",
            "Belgian Shepherd",
            "Belgian Tervuren",
            "Bergamasco Sheepdog",
            "Berger Picard",
            "Bernedoodle",
            "Bernese Mountain Dog",
            "Bichon Frise",
            "Biewer Terrier",
            "Billy",
            "Black and Tan Coonhound",
            "Black Russian Terrier",
            "Bloodhound",
            "Blue Heeler",
            "Blue Lacy (Texas Blue Game Dog)",
            "Bluetick Coonhound",
            "Boerboel",
            "Bohemian Shepherd",
            "Bolognese",
            "Border Collie",
            "Border Collie - Mix",
            "Border Terrier",
            "Borgi",
            "Borkie",
            "Borzoi",
            "Boston Terrier",
            "Bouvier des Flandres",
            "Boxador",
            "Boxer",
            "Boxer - Mix",
            "Boykin Spaniel",
            "Bracco Italiano",
            "Braque - d'Ariege",
            "Braque - Dupuy",
            "Braque - Francais de Petite Taille",
            "Brazilian Molosser",
            "Breed not listed (Canine)",
            "Briard",
            "Brittany", "Broholmer",
            "Bruno de Jura",
            "Brussels Griffon",
            "Bug ( Bugg )",
            "Bull Terrier",
            "Bulldog",
            "Bulldog - Mix",
            "Bullmastiff",
            "Cairn Terrier",
            "Cairnoodle ( Poocan, Cairn-Poo )",
            "Cajun Squirrel Dog", "Canaan Dog",
            "Cane Corso", "Canis Panther", "Canoe Dog",
            "Cardigan Welsh Corgi",
            "Carolina Dog",
            "Catahoula Leopard Dog",
            "Cattle Dog - Australian",
            "Cattle Dog - Entlebuch ( Entlebucher Sennenhund, Entlebucher Mountain Dog )",
            "Cattle Dog - Stumpy Tail",
            "Caucasian Shepherd Dog",
            "Cavachi ( Chilier, Chiller, Cava-Chi )",
            "Cavador", "Cavajack ( Jackalier )",
            "Cavalier King Charles Spaniel",
            "Cavapoo ( Cavoodle, Cavadoodle )",
            "Cavatzu ( Cava-Tzu )",
            "Central Asian Shepherd Dog",
            "Cesky Terrier", "Chesapeake Bay Retriever",
            "Chi-Apso ( Apsochi )",
            "Chi-Poo",
            "Chi-Terrier",
            "Chien Loup",
            "Chihuahua",
            "Chihuahua - Teacup",
            "Chihuahua-Mix",
            "Chihuahua, Long-Haired",
            "Chihuahua, Short-Haired",
            "Chinese Crested",
            "Chinese Crested, Hairless",
            "Chinese Crested, Powder Puff",
            "Chinese Shar-Pei",
            "Chinook",
            "Chippiparai",
            "Chiweenie",
            "Chow Chow",
            "Cirneco Dell 'Etna",
            "Clumber Spaniel",
            "Cockalier ( Cockalier Spaniel )",
            "Cockapoo",
            "Cockatzu",
            "Cocker Spaniel",
            "Collie",
            "Collie - Border",
            "Collie - Mix",
            "Collie - Rough",
            "Collie - Smooth",
            "Coonhound",
            "Corgi - Mix",
            "Corkie",
            "Coton De Tulear",
            "Coydog",
            "Coyote",
            "Croatian Sheepdog",
            "Crossbreed ( Mongrel )",
            "Cur - Black Mouth",
            "Cur - Mountain Stephens Stock",
            "Cur - Mountain, View",
            "Cur - Southern, Blackmouth",
            "Cur - Treeing",
            "Cur - Yellow Black Mouth",
            "Curly-Coated Retriever",
            "Dachshund - Long-Haired",
            "Dachshund - Mix",
            "Dachshund - Smooth-Haired",
            "Dachshund - Wire-Haired",
            "Dachshund (unspecified)",
            "Dachshund, Miniature (unspecified)",
            "Dalmador",
            "Dalmatian",
            "Dalmatian - Mix",
            "Dandie Dinmont Terrier",
            "Deutscher Wachtelhund",
            "Doberman Pinscher",
            "Dogo Argentino",
            "Dogue de Bordeaux",
            "Dutch Shepherd",
            "Elo",
            "English Bulldog",
            "English Cocker Spaniel",
            "English Foxhound",
            "English Setter",
            "English Shepherd",
            "English Springer Spaniel",
            "English Toy Spaniel",
            "Entlebucher Mountain Dog",
            "Feist",
            "Feist - Bench-legged",
            "Feist - Kemmer",
            "Feist - Mix",
            "Feist - Mountain",
            "Feist - Pencil-Tail",
            "Feist - Treeing",
            "Fennec Fox",
            "Field Spaniel",
            "Finnish Lapphund",
            "Finnish Spitz",
            "Flat-Coated Retriever",
            "French Bulldog",
            "French Bulldog - Mix",
            "French Mastiff",
            "French Spaniel",
            "Gascon Saintongeois, Petit",
            "German Longhaired Pointer",
            "German Pinscher",
            "German Shepherd",
            "German Shepherd - Mix",
            "German Shepherd Dog",
            "German Shorthaired Pointer",
            "German Shorthaired Pointer - Mix",
            "German Spitz",
            "German Wirehaired Pointer",
            "Giant Schnauzer",
            "Glen of Imaal Terrier",
            "Golden Retriever",
            "Golden Retriever - Mix",
            "Goldendoodle - Standard",
            "Goldendoodle – Miniature ( Toy )( Mini Groodle )",
            "Goldendoodle – Petite ( Petite Groodle )",
            "Goldendoodle ( Groodle )",
            "Gordon Setter",
            "Grand Basset Griffon Vendéen",
            "Great Dane",
            "Great Pyrenees",
            "Greater Swiss Mountain Dog",
            "Grey Fox",
            "Greyhound",
            "Greyhound - Mix",
            "Griffon - Basset Vendeen, Petit",
            "Griffon - Bleu de Gascogne, Petit",
            "Griffon - Briquet Vendeen",
            "Guejae Gae",
            "Gull Dongs",
            "Gull Ter",
            "Harehound",
            "Harrier",
            "Havanese",
            "Hawaiian Poi Dog",
            "Hound - Balkan",
            "Hound - Bernese",
            "Hound - Bizanian",
            "Hound - Bleu de Gascogne, Petit",
            "Hound - Cretan",
            "Hound - Estonian",
            "Hound - Istrian Coarse-Haired",
            "Hound - Istrian Short-Haired",
            "Hound - Latvian",
            "Hound - Lithuanian",
            "Hound - Majestic Tree",
            "Hound - Mix",
            "Hound - Poitevin",
            "Hound - Posavina",
            "Hound - Serbian ( Balkan ), Tricolour ( Srpski Trobojni Gonic )",
            "Hound - Serbian ( Balkan )(unspecified)",
            "Hound - Sicillian",
            "Hound - Trail",
            "Hound - Transylvanian",
            "Hound - Trigg",
            "Hound - Yugoslavian",
            "Hovawart",
            "Hungarian Kuvasz",
            "Hygenhund",
            "Ibizan Hound",
            "Icelandic Sheepdog",
            "Ilio",
            "Irish Red and White Setter",
            "Irish Red and White Terrier",
            "Irish Setter",
            "Irish Terrier",
            "Irish Water Spaniel",
            "Irish Wolfhound",
            "Italian Greyhound",
            "Italian Mastiff",
            "Jack Russell Terrier",
            "Jack-A-Poo ( Jackapoo, Jackadoodle )",
            "Jack-Chi ( Jackachi, Jackachau, Jackhuahua )",
            "Jackador",
            "Jackal",
            "Jackshit ( Jackashit )",
            "Jackshund ( Jackweenie )",
            "Japanese Chin",
            "Japanese Spitz",
            "Japanese Terrier",
            "Jindo",
            "Kanni",
            "Keeshond",
            "Kemmer Stock Hybrid Squirrel Dog",
            "Kerry Blue Terrier",
            "Khala, Hairless",
            "Kirhiz",
            "Komondor",
            "Kromfohrländer",
            "Kugsha Dog",
            "Kui Mlk",
            "Kuvasz",
            "Kyi-Apso",
            "Kyi-Leo",
            "Labra Doodle",
            "Labradoodle - Australian",
            "Labradoodle - Miniature",
            "Labradoodle - Standard",
            "Labrador Retriever",
            "Labrador Retriever - Mix",
            "Lagotto Romagnolo",
            "Laika - Nenets Herding",
            "Lakedoodle",
            "Lakeland Terrier",
            "Leonberger",
            "Levesque",
            "Lhasa Apso",
            "Loughlander",
            "Lowchen",
            "Lurcher",
            "Maltese",
            "Maltese Mix",
            "Maltipoo",
            "Manchester Terrier",
            "Manchester Terrier - Standard",
            "Manchester Terrier - Toy",
            "Maneto ( Andalusian Hound Maneto, Andalusian Podenco Maneto )",
            "Mastiff",
            "Mastiff - Mix",
            "Mexican Hairless",
            "Mi-Ki",
            "Mini Australian Shepherd",
            "Miniature American Shepherd",
            "Miniature Bull Terrier",
            "Miniature Pinscher",
            "Miniature Pinscher - Mix",
            "Miniature Poodle",
            "Miniature Schnauzer",
            "Mix, Hound",
            "Mixed",
            "Mixed Breed",
            "Morkie (Maltese / Yorkshire Terrier)",
            "Mountain Dog - Styrian, Rough-Haired",
            "Mountain Dog - Styrian, Wire-Haired",
            "Neapolitan Mastiff",
            "Nederlandse Kooikerhondje",
            "New Guinea Singing Dog",
            "New Zealand Heading Dog",
            "Newfoundland",
            "Norfolk Terrier",
            "Norwegian Buhund",
            "Norwegian Elkhound",
            "Norwegian Lundhund",
            "Norwegian Puffin Dog",
            "Norwich Terrier",
            "Nova Scotia Duck Tolling Retriever",
            "Old Danish Bird Dog",
            "Old English Sheepdog",
            "Ori Pei",
            "Other",
            "Otterhound",
            "Ovtcharka - Central Asian",
            "Ovtcharka - Middle Asian",
            "Papillon",
            "Papillon - Mix",
            "Pariah Dog",
            "Parson Russell Terrier",
            "Patterjack",
            "Patterpoo (Patterdoodle)",
            "Pekapoo (Pekingese / Poodle)",
            "Pekingese",
            "Pekingese - Mix",
            "Pembroke Welsh Corgi",
            "Perro de Presa Canario",
            "Petit Basset Griffon Vendeen",
            "Phalène (Butterfly Dog) (Epagneul Nain Continental)",
            "Pharaoh Hound",
            "Pila",
            "Pinscher - Carlin",
            "Pinscher - Harlequin",
            "Pinscher - Swiss, Short-Haired (Glattharidge)",
            "Pinscher – Miniature (Zwergpinscher, Min Pin)",
            "Plott Hound",
            "Podenco (unspecified)",
            "Pointer",
            "Pointer - Mix",
            "Polish Lowland Sheepdog",
            "Pomchi (Pomeranian / Chihuahua)",
            "Pomeranian",
            "Pomeranian - Mix",
            "Pomeranian - Teacup",
            "Pomsky (Pomeranian / Husky)",
            "Poodle",
            "Poodle - Miniature",
            "Poodle - Mix",
            "Poodle - Standard",
            "Poodle - Toy",
            "Portuguese Podengo",
            "Portuguese Podengo Pequeno",
            "Portuguese Water Dog",
            "Pug",
            "Pug - Mix",
            "Puggle (Pug / Beagle)",
            "Puli",
            "Pumi",
            "Purebred cross (Canine)",
            "Pyredoodle (Pyrepoo, Pyreneesdoodle, Pyreneespoo)",
            "Pyrenean Mastiff",
            "Pyrenean Shepherd",
            "Raibs Suns",
            "Rat Terrier",
            "Red Fox",
            "Redbone Coonhound",
            "Retriever - Flat Coated",
            "Retriever - Golden (Golden Retriever)",
            "Retriever - Labrador (Labrador Retriever)",
            "Retriever - Labrador Mix (Labrador Retriever Mix)",
            "Retriever (unspecified)",
            "Rhodesian Ridgeback",
            "Ridgeback - Thai (Mah Thai)",
            "Ridgeback (unspecified)",
            "Rottweiler",
            "Rottweiler - Mix",
            "Russell Terrier",
            "Sage - Ashayeri",
            "Sage - Koochee",
            "Sage - Mazandarani",
            "Sage (unspecified)",
            "Saint Bernard",
            "Saluki",
            "Samoyed",
            "Sanshu Dog",
            "Sapsari (Sapsaldog)",
            "Schipperke",
            "Schnauzer",
            "Schnauzer - Mix",
            "Scottish Deerhound",
            "Scottish Terrier",
            "Sealyham Terrier",
            "Setter - Italian",
            "Setter - Llewellin",
            "Setter (unspecified)",
            "Sharpei",
            "Sheepdog - Atlas (Chien de L' Atlas) (Aidi)",
            "Sheepdog - Bulgarian (Sheepdog - Karakachan)",
            "Sheepdog - Carpathian (Sheepdog - Romanian)",
            "Sheepdog - Catalan ( Gos d'Atura Català, Shepherd - Catalonian )",
            "Sheepdog - Central Asian",
            "Sheepdog - Egyptian (Armant) (Hawara)",
            "Sheepdog - Greek ( Hellenikos Poimenikos, Shepherd Dog - Greek )",
            "Sheepdog - Greek (Hellenikos Poimenikos)",
            "Sheepdog - Istrian (Krasky Ovcar)",
            "Sheepdog - Maremma ( Maremmo-Abruzzese, Sheepdog – Italian )",
            "Sheepdog - Maremma (Maremmo-Abruzzese)",
            "Sheepdog - New Zealand (Sheepdog - Huntaway)",
            "Sheepdog - Norwegian (Sheepdog - Buhund)",
            "Sheepdog - Romanian Bukovina",
            "Sheepdog - Romanian Mioritic",
            "Sheepdog (unspecified)",
            "Shepherd",
            "Shepherd - Mix",
            "Shepherd Dog - Alaskan",
            "Shepherd Dog - Atlas (Perro de Paster del Atlas) (Marokkanischer Schäferhund)",
            "Shepherd Dog - Australian, Miniature",
            "Shepherd Dog - Australian, Standard",
            "Shepherd Dog - Bohemian (Chodsky Pes)",
            "Shepherd Dog - Bulgarian",
            "Shepherd Dog - Central Asian",
            "Shepherd Dog - Dakotah",
            "Shepherd Dog - East-European",
            "Shepherd Dog - Holland (Hollandse Herdershond)",
            "Shepherd Dog - Italian (Pastore Italiano)",
            "Shepherd Dog - Karst",
            "Shepherd Dog - King",
            "Shepherd Dog - Majorca",
            "Shepherd Dog - McNab",
            "Shepherd Dog - Old Time Farm",
            "Shepherd Dog - Shiloh",
            "Shepherd Dog - Yugoslavian (Sharplaninec) (Charplaninatz) (Illyrian) (Mountain Dog)",
            "Shepherd Dog (unspecified)",
            "Shetland Sheepdog",
            "Shiba Inu",
            "ShiChi ( Chi-Shi, Chi-Tzu )",
            "Shichon",
            "Shih Tzu",
            "Shih Tzu - Mix",
            "Shih-Poo (Shih Tzu / Poodle)",
            "Shikoku (Kochi-ken) (Mikawa Inu) (Shika Inu)",
            "Siberian Husky",
            "Siberian Husky - Mix",
            "Silken Windhound",
            "Silky Terrier",
            "Simaku",
            "Skye Terrier",
            "Sloughi",
            "Small Munsterlander",
            "Smooth Fox Terrier",
            "Soft Coated Wheaten Terrier",
            "Spaniel - Continental, Toy",
            "Spaniel - de Pont-Audemer (Epagneul)",
            "Spaniel - Picardy",
            "Spaniel - Water (unspecified)",
            "Spaniel (unspecified)",
            "Spanish Mastiff",
            "Spanish Water Dog",
            "Spinone Italiano",
            "Spitz - Norbotten (Norbottenspets)",
            "Spitz - Nordic",
            "Spitz (unspecified)",
            "Sprockerpoo",
            "Sprointer",
            "Sprollie",
            "Staffordshire Bull Terrier",
            "Standard Poodle",
            "Standard Schnauzer",
            "Stoodle",
            "Sussex Spaniel",
            "Swedish Lapphund",
            "Swedish Vallhund",
            "Swift Fox",
            "Tahltan (Kyrgyz Sighthound)",
            "Tasy",
            "Teacup Poodle",
            "Teddy Roosevelt Terrier",
            "Telomian",
            "Terrier",
            "Terrier - American Pit Bull",
            "Terrier - Balla",
            "Terrier - Mix",
            "Terrier - Welsh",
            "Thai Bangkaew Dog",
            "Tibetan Mastiff",
            "Tibetan Spaniel",
            "Tibetan Terrier",
            "Toy Fox Terrier",
            "Toy Poodle",
            "Treeing Tennessee Brindle",
            "Treeing Walker Coonhound",
            "Unknown",
            "Utonagan",
            "Verelade",
            "Vizsla",
            "Vucciriscu",
            "Waller",
            "Water Dog - St John",
            "Water Dog (unspecified)",
            "Weimaraner",
            "Welsh Corgi - Pembroke",
            "Welsh Springer Spaniel",
            "Welsh Terrier",
            "West Highland White Terrier",
            "Wheaton Terrier",
            "Whippet",
            "Wire Fox Terrier",
            "Wirehaired Pointing Griffon",
            "Wirehaired Vizsla",
            "Wolf",
            "Wolfdog - British",
            "Wolfdog (unspecified)",
            "Wolfhound - Saarloos ( Saarlooswolfhond, Saarloos Wolfdog )",
            "Wolfhound - Saarloos (Saarlooswolfhond)",
            "Wolfhound (unspecified)",
            "Xoloitzcuintli",
            "Yajivy",
            "Yakutian Laika",
            "Yo-Chon",
            "Yorkipoo (Yorkshire Terrier / Poodle)",
            "Yorkshire Terrier",
            "Yorkshire Terrier - Mix");
}
